on:
  push

name: Test Transition Issue

jobs:
    test-transition-issue:
      name: Transition Issue
      runs-on: ubuntu-latest
      steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
      - name: Criar nova issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
            project: "RTECHTH"
            issuetype: Task
            summary: "Build completa para ${{ github.repository }}"

      - name: Transição da issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "Não Iniciado"