on:
  push

name: Test Transition Issue

jobs:
    test-transition-issue:
      name: Transition Issue
      runs-on: ubuntu-latest
      steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
      - name: Create new issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
            project: "MeuProjeto"
            issuetype: "Issue"
            summary: "RTECHTH-2"

      - name: Transition issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "In progress"